name: "Manual - Run test against url"
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Webpage url to test'
        required: true
        default: 'https://webperf.se/'
        type: string
      test:
        description: 'Test to run, comma separated list of numbers'
        required: true
        default: '2,9,15,18,20,21,22,23,24,25,26,27,28,29,30'
        type: string
      language:
        description: 'Setting general.language'
        required: true
        default: 'en'
        type: string
      details:
        description: 'Setting general.review.details'
        required: true
        default: 'true'
        type: string
      data:
        description: 'Setting general.review.data'
        required: true
        default: 'false'
        type: string
      improve:
        description: 'Setting general.review.improve-only'
        required: true
        default: 'true'
        type: string
env:
  TEST_TAG: webperfse/webperf-core:test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Setup QEMU # used to allow multiplatform docker builds
      uses: docker/setup-qemu-action@v3
    - name: Setup Docker Buildx # used to allow multiplatform docker builds
      uses: docker/setup-buildx-action@v3
    - name: Build the Docker image # used to allow multiplatform docker builds
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64
        load: true
        tags: ${{ env.TEST_TAG }}
    - name: Test ${{ github.event.inputs.test }} for ${{ github.event.inputs.url }}
      run: |
        testresult=$(docker run ${{ env.TEST_TAG }} python default.py -t ${{ github.event.inputs.test }} -r --setting general.review.details=${{ github.event.inputs.details }} --setting general.review.data=${{ github.event.inputs.data }} --setting general.review.improve-only=${{ github.event.inputs.improve }} --setting general.language=${{ github.event.inputs.language }} -u ${{ github.event.inputs.url }})
        echo "$testresult"
