# https://github.com/simbo/changes-since-last-release-action
name: Prepare Release
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**software-full.json"
      - "Dockerfile"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # [!] we need to checkout with tags and commit history
      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x" # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: "x64" # optional x64 or x86. Defaults to x64 if not specified
      - name: Setup dependencies using pip
        run: pip install -r requirements.txt
      - name: ðŸ“‹ Get Commits since last Release
        id: changes
        uses: simbo/changes-since-last-release-action@v1.0.1
        with:
          line-prefix: "* "
          include-hashes: false
      - name: Generate new release version
        id: newversion
        run: python default.py --prepare-release "${{ steps.changes.outputs.last-tag }}"
      - name: Create pull request
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: Updated version in package.json to latest
          branch: update-version-in-package-json
          title: "Prepare release - ${{ env.NEW_VERSION }}"
          body: |
            Approving this PR triggers creation of a new release.
            
            Changes since ${{ steps.changes.outputs.last-tag }}:
            ${{ steps.changes.outputs.log }}
          assignees: cockroacher,marcusosterberg
          reviewers: cockroacher,marcusosterberg
          labels: ignore-for-release
          add-paths: |
            package.json
