name: "Regression Test - HTML Validation Test"
on:
  push:
    paths-ignore:
      - '**.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
      if: ${{ success() }}
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: Setup dependencies using pip
      run: pip install -r requirements.txt
      if: ${{ success() }}
    - name: Download vnu.jar (The Nu Html Checker)
      run: wget -q -O vnu.jar https://github.com/validator/validator/releases/download/latest/vnu.jar
    - name: Setup config (using SAMPLE-config.py as config.py)
      run: python .github/workflows/verify_result.py -c true
      if: ${{ success() }}
    - name: Test HTML Validation (true)
      run: |
         python default.py -t 6 -r -u https://webperf.se/ -o .github/workflows/testresult-06.json
         python .github/workflows/verify_result.py -t 6
      if: ${{ success() }}
    - name: Test HTML Validation (true)
      run: |
         python default.py -t 6 -r -u https://www.arbetarbladet.se -o .github/workflows/testresult-06.json
         python .github/workflows/verify_result.py -t 6
      if: ${{ success() }}
    - name: Test HTML Validation (true)
      run: |
         python default.py -t 6 -r -u https://www.hn.se -o .github/workflows/testresult-06.json
         python .github/workflows/verify_result.py -t 6
      if: ${{ success() }}
    - name: Setup config (using SAMPLE-config.py as config.py)
      run: python .github/workflows/verify_result.py -c false
      if: ${{ success() }}
    - name: Test HTML Validation (false)
      run: |
         python default.py -t 6 -r -u https://webperf.se/ -o .github/workflows/testresult-06.json
         python .github/workflows/verify_result.py -t 6
      if: ${{ success() }}
    - name: Test HTML Validation (false)
      run: |
         python default.py -t 6 -r -u https://www.arbetarbladet.se -o .github/workflows/testresult-06.json
         python .github/workflows/verify_result.py -t 6
      if: ${{ success() }}
    - name: Test HTML Validation (false)
      run: |
         python default.py -t 6 -r -u https://www.hn.se -o .github/workflows/testresult-06.json
         python .github/workflows/verify_result.py -t 6
      if: ${{ success() }}