name: "Regression Test - Sitespeed.io - Browsertime.har fields and structure"
on:
  workflow_dispatch:
  push:
    paths:
      - '**verify_browsertime_har.py'
      - '**regression-test-sitespeed-browsertime-har.yml'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
            matrix:
                os: [ubuntu-latest]
                browser: ['firefox', 'chrome']
    steps:
    - name: Check out repository code
      uses: actions/checkout@v6
    - name: Setup python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: Setup dependencies using pip
      run: pip install -r requirements.txt
    - name: Setup QEMU # used to allow multiplatform docker builds
      uses: docker/setup-qemu-action@v3
    - name: Setup Docker Buildx # used to allow multiplatform docker builds
      uses: docker/setup-buildx-action@v3
    - name: Testing sitespeed.io:s browsertime.har output using ${{ matrix.browser }}
      if: always()
      run: |
        sitespeedversion=$(python .github/workflows/verify_result.py --docker-sitespeed-version)
        command="docker run -v $(pwd):/sitespeed.io $sitespeedversion -b ${{ matrix.browser }} -n 1 --chrome.includeResponseBodies all --firefox.includeResponseBodies all https://webperf.se"
        echo "A: $command"
        testresult=$($command)
        echo "B: $testresult"
        path=$(echo "$testresult" | grep -o "/sitespeed.io/.*")
        echo "C: $path"
        if [ -n "$path" ]; then
          har_file=$(ls -t $(find $(pwd) -name "browsertime.har") | head -1)
          echo "D: $har_file"
          if [ -f "$har_file" ]; then
            echo "Found browsertime.har at $har_file"
            python .github/workflows/verify_browsertime_har.py --browsertime $har_file
          else
            echo "Error: browsertime.har not found in $path"
            exit 1
          fi
        else
          echo "Error: No path found starting with /sitespeed.io/"
          exit 1
        fi
    - name: Testing sitespeed.io:s browsertime.har with chrome-cookies.cjs output using ${{ matrix.browser }}
      if: always()
      run: |
        sitespeedversion=$(python .github/workflows/verify_result.py --docker-sitespeed-version)
        command="docker run -v $(pwd):/sitespeed.io $sitespeedversion -b ${{ matrix.browser }} -n 1 --postScript chrome-cookies.cjs https://polisen.se"
        echo "A: $command"
        testresult=$($command)
        echo "B: $testresult"
        path=$(echo "$testresult" | grep -o "/sitespeed.io/.*")
        echo "C: $path"
        if [ -n "$path" ]; then
          har_file=$(ls -t $(find $(pwd) -name "browsertime.har") | head -1)
          echo "D: $har_file"
          if [ -f "$har_file" ]; then
            echo "Found browsertime.har at $har_file"
            cookies=$(echo "$testresult" | grep -o "COOKIES:START")
            echo "E: $cookies"
            if [ -n "$cookies" ]; then
              echo "Cookies found in $har_file"
            else
              echo "Cookies cookie not found in $har_file"
              exit 1
            fi
          else
            echo "Error: browsertime.har not found in $path"
            exit 1
          fi
        else
          echo "Error: No path found starting with /sitespeed.io/"
          exit 1
        fi
    - name: Testing sitespeed.io:s browsertime.har with chrome-versions.cjs output using ${{ matrix.browser }}
      if: always()
      run: |
        sitespeedversion=$(python .github/workflows/verify_result.py --docker-sitespeed-version)
        command="docker run -v $(pwd):/sitespeed.io $sitespeedversion -b ${{ matrix.browser }} -n 1 --postScript chrome-versions.cjs https://webperf.se"
        echo "A: $command"
        testresult=$($command)
        echo "B: $testresult"
        path=$(echo "$testresult" | grep -o "/sitespeed.io/.*")
        echo "C: $path"
        if [ -n "$path" ]; then
          har_file=$(ls -t $(find $(pwd) -name "browsertime.har") | head -1)
          echo "D: $har_file"
          if [ -f "$har_file" ]; then
            echo "Found browsertime.har at $har_file"
            versions=$(echo "$testresult" | grep -o "VERSIONS:START")
            echo "E: $versions"
            if [ -n "$versions" ]; then
              echo "Versions found in $har_file"
            else
              echo "Versions not found in $har_file"
              exit 1
            fi
          else
            echo "Error: browsertime.har not found in $path"
            exit 1
          fi
        else
          echo "Error: No path found starting with /sitespeed.io/"
          exit 1
        fi
