name: "Regression Test - Google Lighthouse Based Test(s)"
on:
  push:
    paths-ignore:
      - '**.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
      if: ${{ success() }}
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: Setup dependencies using pip
      run: pip install -r requirements.txt
      if: ${{ success() }}
    - name: Setup node (ONLY used for Yellow Lab Tools AND lighthouse)
      uses: actions/setup-node@v3
    - name: Setup lighthouse npm package (ONLY used for lighthouse)
      run: npm install -g lighthouse
      if: ${{ success() }}
    - name: Setup config (using SAMPLE-config.py as config.py)
      run: python .github/workflows/verify_result.py -c false
      if: ${{ success() }}
    - name: Test Performance (Google Lighthouse)
      run: |
         python default.py -t 1 -r -u https://webperf.se/ -o .github/workflows/testresult-01.json
         python .github/workflows/verify_result.py -t 1
      if: ${{ success() }}
    - name: Test SEO (Google Lighthouse)
      run: |
         python default.py -t 4 -r -u https://webperf.se/ -o .github/workflows/testresult-04.json
         python .github/workflows/verify_result.py -t 4
      if: ${{ success() }}
    - name: Test Best Practice (Google Lighthouse)
      run: |
         python default.py -t 5 -r -u https://webperf.se/ -o .github/workflows/testresult-05.json
         python .github/workflows/verify_result.py -t 5
      if: ${{ success() }}
    - name: Test PWA (Google Lighthouse)
      run: |
         python default.py -t 8 -r -u https://webperf.se/ -o .github/workflows/testresult-08.json
         python .github/workflows/verify_result.py -t 8
      if: ${{ success() }}
    - name: Test Energy Efficiency (Website Carbon Calculator)
      run: |
         python default.py -t 22 -r -u https://webperf.se/ -o .github/workflows/testresult-22.json
         python .github/workflows/verify_result.py -t 22
      if: ${{ success() }}