name: "Regression Test - Quality on frontend (Yellow Lab Tools) Test"
on:
  push:
    paths-ignore:
      - '**.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
      if: ${{ success() }}
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: Setup dependencies using pip
      run: pip install -r requirements.txt
      if: ${{ success() }}
    - name: Setup node (ONLY used for Yellow Lab Tools)
      uses: actions/setup-node@v2
    - name: Setup node dependencies (ONLY used for Yellow Lab Tools)
      run: npm install -g node-gyp
    - name: Setup libjpeg and fontconfig (ONLY used for Yellow Lab Tools)
      run: sudo apt-get install libjpeg-dev libfontconfig
      shell: bash
    - name: Setup yellowlabtools npm package (ONLY used for Yellow Lab Tools)
      run: npm install -g yellowlabtools
    - name: Setup config (using SAMPLE-config.py as config.py)
      run: python .github/workflows/verify_result.py -c
      if: ${{ success() }}
    # We are saving this entry here because hopefully we will later be able to use same tech
    # - name: Test Performance (Sitespeed.io)
    #   run: |
    #      python default.py -t 15 -r -u https://webperf.se/ -o .github/workflows/testresult-15.json
    #      python .github/workflows/verify_result.py -t 15
    #   if: ${{ success() }}
    - name:  Quality on frontend (Yellow Lab Tools)
      run: |
         python default.py -t 17 -r -u https://webperf.se/ -o .github/workflows/testresult-17.json
         python .github/workflows/verify_result.py -t 17
      if: ${{ success() }}
